"""
Django settings for paystackcollection project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import django.apps.registry
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@5=4p3zgbecoucli)h@!*0^+-gg*(8oey+lj)zu$62zgsz_ym4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
LOCALHOST = False


# Application definition
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_crontab',

    'graphene_django',
    'graphql',
    'rest_framework',
    'django_filters',
    'easy_pdf',

    'gateways',
    'mandates',
    'users',
    'common',
    'staff',
    'customers',
    'pipeline',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'graphql_jwt.backends.JSONWebTokenBackend',
    'django.contrib.auth.backends.ModelBackend',
]

CRONJOBS = [
    # fetch rentals from paystack every 6 hours starting from midnight
    (
        '0 0,6,12,13,18 * * *',
        'utils.cron.fetch_paystack_payments',
        '>> /tmp/cron-jobs/collections/fetch_paystack_payments.log'
    ),
    # fetch trials from paystack every 10 minutes
    (
        '*/10 * * * *',
        'utils.cron.confirm_trials_status',
        '>> /tmp/cron-jobs/collections/confirm_trials_status.log'
    ),
    # send weekly reports every Wednesday at 10:00 PM
    (
        '0 22 * * 03',
        'utils.cron.send_weekly_report',
        '>> /tmp/cron-jobs/collections/send_weekly_report.log'
    ),

    # ('0 6 * * *', 'utils.cron.fail_paystack_payments')  # everyday at 6:00 AM
]

GRAPHENE = {
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
}

ROOT_URLCONF = 'paystackcollection.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'paystackcollection/templates'),
            os.path.join(BASE_DIR, 'utils/templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'paystackcollection.wsgi.application'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'Collections',
        'TIMEOUT': 60 * 60,
        'OPTIONS': {
            'MAX_ENTRIES': 10,
            'CULL_FREQUENCY': 1
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': "{}{}".format(
            'django.contrib.auth.password_validation',
            '.UserAttributeSimilarityValidator'
        )
    },
    {
        'NAME': "{}{}".format(
            'django.contrib.auth.password_validation',
            '.MinimumLengthValidator')
    },
    {
        'NAME': "{}{}".format(
            'django.contrib.auth.password_validation',
            '.CommonPasswordValidator')
    },
    {
        'NAME': "{}{}".format(
            'django.contrib.auth.password_validation',
            '.NumericPasswordValidator')
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


# payment options


EMAIL_HOST = 'smtp.pepipost.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'rosabon'
EMAIL_HOST_PASSWORD = 'rosabon_a3ff18828b58fc335aeb9b8212df9890'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "info@rosabon-finance.com"
DEFAULT_FROM_NAME = "PAYSTACK COLLECTIONS PORTAL"

if DEBUG is True and LOCALHOST is True:
    import paystackcollection.localhost as host
elif DEBUG is True and LOCALHOST is False:
    import paystackcollection.staging as host
elif DEBUG is False and LOCALHOST is False:
    import paystackcollection.production as host
else:
    pass


PAYSTACK_CALLBACK_URL = host.PAYSTACK_CALLBACK_URL
# PAYSTACK_CALLBACK_PAGE = host.PAYSTACK_CALLBACK_PAGE
PAYSTACK_CALLBACK_PAGE = 'https://www.rosabon-finance.com/'
PAYSTACK_MIN_AMOUNT = host.PAYSTACK_MIN_AMOUNT
PAYSTACK_MAX_AMOUNT = host.PAYSTACK_MAX_AMOUNT
PAYSTACK_INITIAL_FEE = host.PAYSTACK_INITIAL_FEE

RENTAL_WIDTH_IN_DAYS = host.RENTAL_WIDTH_IN_DAYS

ALLOWED_HOSTS = host.ALLOWED_HOSTS
CORS_ORIGIN_WHITELIST = host.CORS_ORIGIN_WHITELIST

DATABASES = host.DATABASES
PAYSTACK_AUTHORIZATION_KEY = host.PAYSTACK_AUTHORIZATION_KEY
STATIC_URL = host.STATIC_URL
MEDIA_URL = host.MEDIA_URL
MEDIA_ROOT = host.MEDIA_ROOT
STATIC_ROOT = host.STATIC_ROOT
FRONT_END = host.FRONT_END
REMITTA = host.REMITTA


PDF = 'PDF',
EXCEL = 'EXCEL'

FILETYPES = [
    (PDF, 'PDF'),
    (EXCEL, 'EXCEL'),
]

SAVE_CLICKED = "SAVE CLICKED"
CANCEL_CLICKED = "CANCEL CLICKED"
DECLINE_CLICKED = "DECLINE CLICKED"
APPROVE_CLICKED = "APPROVE CLICKED"
BTN_ACTIONS = [
    SAVE_CLICKED,
    DECLINE_CLICKED,
    CANCEL_CLICKED,
    APPROVE_CLICKED,
]

# ASGI_APPLICATION = 'paystackcollection.routing.application'
