"""
Django settings for paystackcollection project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import django.apps.registry
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@5=4p3zgbecoucli)h@!*0^+-gg*(8oey+lj)zu$62zgsz_ym4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
LOCALHOST = False


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_crontab',

    'graphene_django',
    'graphql',
    'rest_framework',
    'django_filters',
    'easy_pdf',

    'gateways',
    'mandates',
    'users',
    'common',
    'staff',
    'customers',
    'pipeline',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'graphql_jwt.backends.JSONWebTokenBackend',
    'django.contrib.auth.backends.ModelBackend',
]

CRONJOBS = [
    # fetch rentals from paystack every 6 hours
    ('0 */6 * * *', 'utils.cron.fetch_paystack_payments'),
    # fetch trials from paystack every 15 minutes
    ('*/15 * * * *', 'utils.cron.fetch_paystack_payments'),
    ('0 6 * * *', 'utils.cron.fail_paystack_payments')  # everyday at 6:00 AM
]

GRAPHENE = {
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
}

ROOT_URLCONF = 'paystackcollection.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'paystackcollection/templates'),
            os.path.join(BASE_DIR, 'utils/templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'paystackcollection.wsgi.application'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'Collections',
        'TIMEOUT': 60 * 60,
        'OPTIONS': {
            'MAX_ENTRIES': 10,
            'CULL_FREQUENCY': 1
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


# payment options


EMAIL_HOST = 'smtp.pepipost.com'
EMAIL_PORT = '22'
EMAIL_HOST_USER = 'rosabon'
EMAIL_HOST_PASSWORD = 'rosabon_a3ff18828b58fc335aeb9b8212df9890'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "info@rosabon-finance.com"
DEFAULT_FROM_NAME = "-- COLLECTIONS --"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'collections_march_13_2020_09_48',
        'HOST': 'localhost',
        'USER': 'vxtcj5QTKVVgh88C',
        'PASSWORD': '5UofE0dP44cLIh87#csOBhQm7qLQ5nEMD',
        'PORT': ''
    },
    'replica': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'collections_march_13_2020_09_48',
        'HOST': 'localhost',
        'USER': 'vxtcj5QTKVVgh88C',
        'PASSWORD': '5UofE0dP44cLIh87#csOBhQm7qLQ5nEMD',
        'PORT': '',
        'TEST': {
            'MIRROR': 'default'
        }
    },
}

ALLOWED_HOSTS = [
    '157.245.8.141',
    '127.0.0.1',
    'localhost',
]

CORS_ORIGIN_WHITELIST = [
    "http://157.245.8.141",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3002",
]

PAYSTACK_AUTHORIZATION_KEY = 'sk_test_f19608000e260b953cc4af43a6054eac641738b7'
PAYSTACK_CALLBACK_URL = 'https://treasury-dev.concept-nova.com/api.collections/paystack.verification/'
PAYSTACK_CALLBACK_PAGE = 'https://www.rosabon-finance.com/'
PAYSTACK_MIN_AMOUNT = 100000  # 1,000.00 NGN
PAYSTACK_MAX_AMOUNT = 490000  # 4,900.00 NGN
PAYSTACK_INITIAL_FEE = 5000  # 50 NGN


RENTAL_WIDTH_IN_DAYS = 60
# FRONT_END = 'http://157.245.8.141/collections'
FRONT_END = 'https://coll.concept-nova.com/'
#FRONT_END = 'https://treasury-dev.concept-nova.com/collections'

STATIC_URL = '/collections.static/'
MEDIA_URL = '/collections.media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

REMITTA = "http://www.remitademo.net/remita/exapp/api/v1/send/api/echannelsvc/echannel/"


PDF = 'PDF',
EXCEL = 'EXCEL'

FILETYPES = [
    (PDF, 'PDF'),
    (EXCEL, 'EXCEL'),
]

SAVE_CLICKED = "SAVE CLICKED"
CANCEL_CLICKED = "CANCEL CLICKED"
DECLINE_CLICKED = "DECLINE CLICKED"
APPROVE_CLICKED = "APPROVE CLICKED"
BTN_ACTIONS = [
    SAVE_CLICKED,
    DECLINE_CLICKED,
    CANCEL_CLICKED,
    APPROVE_CLICKED,
]

# ASGI_APPLICATION = 'paystackcollection.routing.application'
